/*
SQLyog Ultimate v11.24 (32 bit)
MySQL - 5.5.32-log : Database - m_school
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`m_school` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `m_school`;

/*Table structure for table `admin_performance_teacher` */

DROP TABLE IF EXISTS `admin_performance_teacher`;

CREATE TABLE `admin_performance_teacher` (
  `REF` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键，删除或者更新用',
  `CLASS_ID` int(11) NOT NULL COMMENT '班级id',
  `COURSE_ID` bigint(20) NOT NULL COMMENT '专题id',
  `COURSE_NAME` varchar(1000) NOT NULL COMMENT '专题名称',
  `TASK_NUM` int(11) DEFAULT NULL COMMENT '任务数量',
  `END_TASK_NUM` int(11) DEFAULT NULL COMMENT '结束任务数量',
  `COMPLETE_RATE` varchar(100) DEFAULT NULL COMMENT '任务完成率',
  `EVALUATION` varchar(100) DEFAULT NULL COMMENT '专题评价平均分',
  `RESOURCE_TASK` varchar(500) DEFAULT NULL COMMENT '资源学习类任务',
  `INTERACTIVE_TASK` varchar(500) DEFAULT NULL COMMENT '互动交流任务',
  `MICRO_TASK` varchar(500) DEFAULT NULL COMMENT '微课程任务',
  `COILINGTEST_TASK` varchar(500) DEFAULT NULL COMMENT '成卷测试任务',
  `SELFTEST_TASK` varchar(500) DEFAULT NULL COMMENT '自主测试任务',
  `LIVE_TASK` varchar(500) DEFAULT NULL COMMENT '直播课任务',
  `QUES_TASK` varchar(500) DEFAULT NULL COMMENT '试题任务',
  `GENERAL_TASK` varchar(500) DEFAULT NULL COMMENT '一般任务',
  `GRADE_ID` int(11) DEFAULT NULL COMMENT '年级',
  `SUBJECT_ID` int(11) DEFAULT NULL COMMENT '学科',
  `COURSE_TIME` datetime DEFAULT NULL COMMENT '专题时间',
  PRIMARY KEY (`REF`)
) ENGINE=MyISAM AUTO_INCREMENT=2724 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
